using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace Reflectable
{
    public enum ReflectableBlockType { Normal, Tough, Armored, Elite, Anchor, Gem, Bomb, Boss }
    [Serializable] public class ReflectableCellSave { public int row, column, hp, maxHp; public ReflectableBlockType type; }
    [Serializable] public class ReflectableRunSave { public bool valid; public int stage, turn, hp, maxHp, score, gems, level, exp, skillPoints, power, ricochet, extraBall, maxCombo, destroyed, stageBlocks, ricochets, lightDamage, lightRange, lightPierce; public string character; public int rank; public List<ReflectableCellSave> blocks = new List<ReflectableCellSave>(); }
    public sealed class ReflectableGameController : MonoBehaviour
    {
        [Header("Scene references")][SerializeField] Camera gameCamera; [SerializeField] Transform player, firePoint, gridOrigin, blocksRoot, projectilesRoot, stageVisualContainer; [SerializeField] LineRenderer aimPreview;
        [SerializeField] GameObject normalBlockPrefab, gemBlockPrefab, bombBlockPrefab, projectilePrefab;
        [Header("Arena")][SerializeField] float left = -7f, right = 7f, ceiling = 5.2f, bottom = -5.4f;
        [Header("Grid")][SerializeField, Min(1)] int columns = 7, rows = 10; [SerializeField] Vector2 cellSpacing = new Vector2(1.85f, 1.22f);
        [Header("UI")][SerializeField] Text hpText, scoreText, gemsText, turnText, comboText, levelText, characterText, gameOverText; [SerializeField] GameObject pausePanel, pauseSettingsPanel, mainMenuConfirmPanel, gameOverPanel, upgradePanel, characterPanel, stageIntro; [SerializeField] Button powerButton, ricochetButton, extraBallButton, characterButton, skipTurnButton, pauseButton; [SerializeField] PlayerCharacterPresenter characterPresenter; [SerializeField] CharacterGachaUI characterGacha; [SerializeField] GameplayHudController gameplayHud;
        [Header("Balance")][SerializeField] float projectileSpeed = 12f; [SerializeField] int baseDamage = 10; [SerializeField] float launchSpacing = .09f; [SerializeField] GameplayFeedbackManager feedback;
        enum TurnState { Aiming, Firing, Resolving, Paused, GameOver }
        readonly List<ReflectableBlockView> blocks = new List<ReflectableBlockView>();
        readonly HashSet<int> activeProjectileIds = new HashSet<int>();
        readonly Dictionary<int,int> burningBlocks = new Dictionary<int,int>();
        int turn,hp,maxHp,score,gems,level,exp,skillPoints,power,ricochet,extraBall,combo,maxCombo,destroyed,ricochets,rank,stage,stageBlocks,nextBossThreshold,bossNumber,lightDamage,lightRange,lightPierce; string character=CharacterProgression.StarterId; GameObject activeStageVisual; bool aiming,ending,gameOver,turnFired,stageCleared,stageClearPending,skippingTurn,bossActive,bossQueued,finalBossActive,stageTransitioning; [SerializeField] bool drawPlayerDamageDebug; int activeProjectiles; TurnState state, pausedState;
        float nyxDamageBonus,nyxRicochetBonus,nyxCriticalBonus;int nyxExtraBalls,nyxGemBonus;Coroutine gachaRoutine;
        string SavePath => Path.Combine(Application.persistentDataPath,"reflectable_run.json");
        string SaveBackupPath => SavePath+".bak";
        string SaveTempPath => SavePath+".tmp";
        public int CurrentHP => hp;
        public int MaxHP => maxHp;
        public event Action<int, int> HealthChanged;
        public void Configure(Transform scenePlayer,Transform sceneFirePoint,Transform sceneGridOrigin,Transform sceneBlocksRoot,Transform sceneProjectilesRoot,LineRenderer scenePreview,GameObject normal,GameObject gem,GameObject bomb,GameObject projectile,Text hpLabel,Text scoreLabel,Text gemLabel,Text turnLabel,Text comboLabel,Text levelLabel,Text characterLabel,Text overLabel,GameObject pause,GameObject over,GameObject upgrades,GameObject characters){player=scenePlayer;firePoint=sceneFirePoint;gridOrigin=sceneGridOrigin;blocksRoot=sceneBlocksRoot;projectilesRoot=sceneProjectilesRoot;aimPreview=scenePreview;normalBlockPrefab=normal;gemBlockPrefab=gem;bombBlockPrefab=bomb;projectilePrefab=projectile;hpText=hpLabel;scoreText=scoreLabel;gemsText=gemLabel;turnText=turnLabel;comboText=comboLabel;levelText=levelLabel;characterText=characterLabel;gameOverText=overLabel;pausePanel=pause;gameOverPanel=over;upgradePanel=upgrades;characterPanel=characters;}
        void Awake()
        {
            if (ValidatePersistentReferences()) return;
            enabled = false;
            Debug.LogError("ReflectableGameController disabled because the saved Game scene has missing persistent references.", this);
        }
        void Start(){Application.targetFrameRate=120;Time.timeScale=1;feedback?.BindCharacter(characterPresenter);if(pausePanel)pausePanel.SetActive(false);if(pauseSettingsPanel)pauseSettingsPanel.SetActive(false);if(mainMenuConfirmPanel)mainMenuConfirmPanel.SetActive(false);if(gameOverPanel)gameOverPanel.SetActive(false);if(upgradePanel)upgradePanel.SetActive(false);if(characterPanel)characterPanel.SetActive(false);if(PlayerPrefs.GetInt("ReflectableContinue",0)==1){PlayerPrefs.DeleteKey("ReflectableContinue");ContinueGame();}else StartNewRun();}
        bool ValidatePersistentReferences()
        {
            bool valid = true;
            UnityEngine.Object[] required = { gameCamera, player, firePoint, gridOrigin, blocksRoot, projectilesRoot, stageVisualContainer, aimPreview, normalBlockPrefab, gemBlockPrefab, bombBlockPrefab, projectilePrefab, hpText, scoreText, gemsText, turnText, comboText, levelText, characterText, gameOverText, pausePanel, pauseSettingsPanel, mainMenuConfirmPanel, gameOverPanel, upgradePanel, characterPanel, stageIntro, powerButton, ricochetButton, extraBallButton, characterButton, skipTurnButton, pauseButton, characterPresenter, characterGacha, gameplayHud, feedback };
            foreach (var reference in required) if (!reference) { valid = false; break; }
            if (!valid) Debug.LogError("The Game scene contains an unassigned ReflectableGameController reference. Run Tools/Project Validation for the exact field.", this);
            if (characterPresenter && !characterPresenter.Database) { valid = false; Debug.LogError("PlayerCharacterPresenter has no persistent CharacterDatabase reference.", characterPresenter); }
            if (characterGacha && !characterGacha.HasPersistentReferences) { valid = false; Debug.LogError("CharacterGachaUI has missing persistent banner or reveal references.", characterGacha); }
            return valid;
        }
        void Update(){if(gameOver)return;var mouse=Mouse.current;if(Keyboard.current!=null&&Keyboard.current.escapeKey.wasPressedThisFrame){if(mainMenuConfirmPanel&&mainMenuConfirmPanel.activeInHierarchy)CancelMainMenu();else if(pauseSettingsPanel&&pauseSettingsPanel.activeInHierarchy)ClosePauseSettings();else TogglePause();}if(!GameplayInputEnabled||mouse==null)return;Vector3 world=gameCamera.ScreenToWorldPoint(mouse.position.ReadValue());Vector2 dir=(Vector2)(world-firePoint.position);dir.y=Mathf.Max(.2f,dir.y);dir.Normalize();DrawPreview(dir);if(mouse.leftButton.wasPressedThisFrame&&!PointerOverUI())StartCoroutine(Fire(dir));}
        bool GameplayInputEnabled=>state==TurnState.Aiming&&aiming&&Time.timeScale>0&&!AnyModalOpen();
        bool CanSkipTurn=>(state==TurnState.Aiming||state==TurnState.Firing)&&!skippingTurn&&!stageTransitioning&&!gameOver&&Time.timeScale>0&&!AnyModalOpen();
        bool AnyModalOpen()=>(pausePanel&&pausePanel.activeInHierarchy)||(gameOverPanel&&gameOverPanel.activeInHierarchy)||(upgradePanel&&upgradePanel.activeInHierarchy)||(characterPanel&&characterPanel.activeInHierarchy);
        void RefreshSkipTurnButton(){if(skipTurnButton)skipTurnButton.interactable=CanSkipTurn;}
        static bool PointerOverUI()=>EventSystem.current!=null&&EventSystem.current.IsPointerOverGameObject();
        public void StartNewGame()=>StartNewRun();
        public void StartNewRun(){StopAllCoroutines();Time.timeScale=1;feedback?.ComboEnded(combo);ResolveActiveProjectiles(false);ClearBlocks();SetHealth(100,100);score=gems=exp=skillPoints=power=ricochet=extraBall=combo=maxCombo=destroyed=ricochets=lightDamage=lightRange=lightPierce=0;level=1;CharacterProgression.MigrateLegacyData();character=CharacterProgression.ActiveCharacterId;rank=CharacterProgression.ActiveCharacterLevel;if(characterPresenter&&characterPresenter.Database&&!characterPresenter.Database.Find(character)){character=CharacterProgression.StarterId;rank=1;CharacterProgression.SetActiveCharacter(character,rank);}characterPresenter?.Present(character);feedback?.BindCharacter(characterPresenter);gameOver=false;StartStage(ReflectableStageSession.ResolveSelectedStage());}
        void StartStage(int nextStage){StopAllCoroutines();Time.timeScale=1;feedback?.ComboEnded(combo);ResolveActiveProjectiles(false);ClearBlocks();stage=Mathf.Clamp(nextStage,1,ReflectableStageConfig.StageCount);ReflectableStageSession.SelectedStage=stage;turn=0;combo=0;stageBlocks=0;bossNumber=0;nextBossThreshold=ReflectableStageConfig.For(stage).BossInterval;bossActive=bossQueued=finalBossActive=false;stageCleared=stageClearPending=false;aiming=false;ending=false;turnFired=false;skippingTurn=false;state=TurnState.Resolving;stageTransitioning=true;if(pausePanel)pausePanel.SetActive(false);if(pauseSettingsPanel)pauseSettingsPanel.SetActive(false);if(mainMenuConfirmPanel)mainMenuConfirmPanel.SetActive(false);if(gameOverPanel)gameOverPanel.SetActive(false);ApplyStageVisual();UpdatePauseButton();SpawnStartingBlocks(stage);RefreshUI();Save();StartCoroutine(StageIntroRoutine());}
        public void ContinueGame()
        {
            if (!File.Exists(SavePath)) { StartNewRun(); return; }
            if (TryReadSave(SavePath, out var data)) { Restore(data); return; }
            Debug.LogWarning("[Save] Primary run save is invalid. Attempting the last atomic backup.");
            if (TryReadSave(SaveBackupPath, out data)) { Restore(data); Save(); return; }
            Debug.LogError("[Save] No valid run save could be recovered. Starting a new run.");
            StartNewRun();
        }
        static bool TryReadSave(string path,out ReflectableRunSave data)
        {
            data=null;
            if(!File.Exists(path))return false;
            try{data=JsonUtility.FromJson<ReflectableRunSave>(File.ReadAllText(path));return data!=null&&data.valid&&data.blocks!=null;}
            catch(Exception exception){Debug.LogWarning("[Save] Failed to read "+path+": "+exception.Message);return false;}
        }
        void Restore(ReflectableRunSave d){ClearBlocks();stage=Mathf.Clamp(d.stage>0?d.stage:ReflectableStageSession.ResolveSelectedStage(),1,ReflectableStageConfig.StageCount);ReflectableStageSession.SelectedStage=stage;ApplyStageVisual();turn=d.turn;SetHealth(Mathf.Min(d.hp,100),100);score=d.score;gems=d.gems;level=d.level;exp=d.exp;skillPoints=d.skillPoints;power=d.power;ricochet=d.ricochet;extraBall=d.extraBall;maxCombo=d.maxCombo;destroyed=d.destroyed;ricochets=d.ricochets;lightDamage=d.lightDamage;lightRange=d.lightRange;lightPierce=d.lightPierce;var target=ReflectableStageConfig.For(stage).BlockTarget;stageBlocks=Mathf.Clamp(d.stageBlocks,0,target);nextBossThreshold=((stageBlocks/ReflectableStageConfig.For(stage).BossInterval)+1)*ReflectableStageConfig.For(stage).BossInterval;bossActive=finalBossActive=false;bossQueued=false;stageCleared=false;stageClearPending=stageBlocks>=target;character=string.IsNullOrEmpty(d.character)?CharacterProgression.ActiveCharacterId:d.character.ToLowerInvariant();bool migratedCharacter=characterPresenter&&characterPresenter.Database&&!characterPresenter.Database.Find(character);if(migratedCharacter){Debug.LogWarning("[Save] Unknown legacy character '"+character+"' migrated to "+CharacterProgression.StarterId+".");character=CharacterProgression.StarterId;}rank=Mathf.Max(1,d.rank);CharacterProgression.SetActiveCharacter(character,rank);characterPresenter?.Present(character);feedback?.BindCharacter(characterPresenter);foreach(var c in d.blocks)CreateBlock(c.row,c.column,c.hp,c.maxHp,c.type);if(migratedCharacter)Save();if(stageClearPending){StartCoroutine(StageClearRoutine());return;}CheckBossMilestone();RefreshUI();BeginTurn();}
        void BeginTurn(){turn++;int completedCombo=combo;combo=0;feedback?.ComboEnded(completedCombo);turnFired=false;activeProjectileIds.Clear();activeProjectiles=0;ending=false;RollNyxBuff();if(character=="sakura"&&turn%4==0&&hp<maxHp)SetHealth(Mathf.Min(maxHp,hp+5),maxHp);state=TurnState.Aiming;aiming=true;if(aimPreview)aimPreview.enabled=true;UpdatePauseButton();RefreshUI();Debug.Log("[Turn] Ready Turn "+turn);}
        IEnumerator Fire(Vector2 direction){if(state!=TurnState.Aiming)yield break;aiming=false;state=TurnState.Firing;turnFired=true;RefreshSkipTurnButton();if(aimPreview)aimPreview.enabled=false;StartCoroutine(PlayerRecoil());int count=1+extraBall+(character=="stella"?1:0)+nyxExtraBalls;activeProjectileIds.Clear();activeProjectiles=0;Debug.Log("[Turn] Shooting | Damage "+ProjectileDamage());for(int i=0;i<count&&state==TurnState.Firing&&turnFired;i++){var go=Instantiate(projectilePrefab,firePoint.position,Quaternion.identity,projectilesRoot);var projectile=go.GetComponent<ReflectableProjectile>();RegisterProjectile(projectile);projectile.Launch(this,direction,projectileSpeed,ProjectileDamage());yield return new WaitForSeconds(launchSpacing);}Debug.Log("[Turn] Active projectiles: "+activeProjectiles);}
        int ProjectileDamage()=>Mathf.Max(1,Mathf.RoundToInt(ReflectableGameBalance.ProjectileDamage(power)*(1f+nyxDamageBonus)));
        void RegisterProjectile(ReflectableProjectile projectile){if(!projectile)return;activeProjectileIds.Add(projectile.GetInstanceID());activeProjectiles=activeProjectileIds.Count;feedback?.RegisterProjectile(projectile);Debug.Log("[Projectile] Registered ID "+projectile.GetInstanceID());}
        public bool IsFinalProjectile(ReflectableProjectile projectile)=>projectile&&activeProjectileIds.Count==1&&activeProjectileIds.Contains(projectile.GetInstanceID());
        public void ProjectileFinished(ReflectableProjectile projectile,float returnX){if(!projectile||!activeProjectileIds.Remove(projectile.GetInstanceID()))return;feedback?.UnregisterProjectile(projectile);activeProjectiles=activeProjectileIds.Count;Debug.Log("[Projectile] Finished ID "+projectile.GetInstanceID()+" | [Turn] Active projectiles: "+activeProjectiles);if(!turnFired||state!=TurnState.Firing)return;StartCoroutine(MovePlayerToReturn(returnX));if(activeProjectiles==0&&!ending&&!gameOver){state=TurnState.Resolving;RefreshSkipTurnButton();Debug.Log("[Turn] Completing Turn "+turn);StartCoroutine(EndTurn());}}
        IEnumerator EndTurn(){if(ending||state!=TurnState.Resolving)yield break;ending=true;Debug.Log("[Turn] Advancing board");yield return new WaitForSeconds(.35f);ApplyBurnDamage();float moveDuration=Mathf.Lerp(.48f,.25f,Mathf.Clamp01(turn/80f));foreach(var b in blocks.ToArray()){if(!b)continue;b.Row++;StartCoroutine(b.MoveTo(CellPosition(b.Row,b.Column),moveDuration));}yield return new WaitForSeconds(moveDuration);Physics2D.SyncTransforms();foreach(var b in blocks.ToArray()){if(!b)continue;if(BlockReachedPlayerDamagePlane(b)){Debug.Log("[BlockDamage] Block ID "+b.GetInstanceID()+" crossed the player damage plane.");DamagePlayerFromBlock(b);if(gameOver)yield break;}else if(b.Row>=rows+1)ResolveMissedPlayerBlock(b,true);}if(stageClearPending){yield return StageClearRoutine();yield break;}SpawnRow(0);Save();ending=false;BeginTurn();}
        void SpawnRow(int row){var definition=ReflectableStageConfig.For(stage);if(stageCleared||stageClearPending||stageTransitioning||stageBlocks>=definition.BlockTarget)return;var patterns=new[]{new[]{1,5},new[]{0,2,5},new[]{1,3,5},new[]{0,1,5,6},new[]{0,3,6},new[]{0,2,4,6}};var cols=patterns[UnityEngine.Random.Range(0,patterns.Length)];float progress=stageBlocks/(float)definition.BlockTarget;int allowed=Mathf.Clamp(Mathf.RoundToInt(Mathf.Lerp(definition.EarlyBlocksPerTurn,definition.LateBlocksPerTurn,progress)),1,columns);var used=new HashSet<int>();foreach(var col in cols){if(used.Count>=allowed)break;used.Add(col);}while(used.Count<Mathf.Min(allowed,cols.Length)&&UnityEngine.Random.value<.5f)used.Add(UnityEngine.Random.Range(0,columns));foreach(var col in used){var type=RollBlockType();int h=BlockHealth(type);CreateBlock(row,col,h,h,type);}}
        ReflectableBlockType RollBlockType(){var definition=ReflectableStageConfig.For(stage);float progress=stageBlocks/(float)definition.BlockTarget;float roll=UnityEngine.Random.value;float gemChance=definition.GemChance*(character=="iris"?1.75f:1f);if(roll<gemChance)return ReflectableBlockType.Gem;if(roll<gemChance+definition.BombChance)return ReflectableBlockType.Bomb;if(progress<.25f)return roll<.80f?ReflectableBlockType.Normal:ReflectableBlockType.Tough;if(progress<.50f)return roll<.55f?ReflectableBlockType.Normal:roll<.85f?ReflectableBlockType.Tough:ReflectableBlockType.Armored;if(progress<.75f)return roll<.40f?ReflectableBlockType.Normal:roll<.72f?ReflectableBlockType.Tough:roll<.94f?ReflectableBlockType.Armored:ReflectableBlockType.Elite;return roll<.43f?ReflectableBlockType.Normal:roll<.73f?ReflectableBlockType.Tough:roll<.93f?ReflectableBlockType.Armored:roll<.98f?ReflectableBlockType.Elite:ReflectableBlockType.Anchor;}
        int BlockHealth(ReflectableBlockType type)=>Mathf.Max(1,ReflectableGameBalance.BlockHp(stage,stageBlocks,type));
        void SpawnStartingBlocks(int stage){var definition=ReflectableStageConfig.For(stage);var opening=new[]{new Vector2Int(0,1),new Vector2Int(0,5),new Vector2Int(1,3),new Vector2Int(1,0),new Vector2Int(1,6)};for(int i=0;i<Mathf.Min(definition.StartingBlockCount,opening.Length);i++){var type=i==1?ReflectableBlockType.Tough:i==2?ReflectableBlockType.Gem:ReflectableBlockType.Normal;int hp=BlockHealth(type);CreateBlock(opening[i].x,opening[i].y,hp,hp,type);}Debug.Log("Reflectable: Stage "+stage+" spawned progression opening.");}
        void CreateBlock(int row,int column,int currentHp,int maximumHp,ReflectableBlockType type){var definition=ReflectableStageConfig.For(stage);var data=ReflectableBlockVisualCatalog.For(type);var prefab=data&&data.prefab?data.prefab:type==ReflectableBlockType.Gem?gemBlockPrefab:type==ReflectableBlockType.Bomb?bombBlockPrefab:normalBlockPrefab;var view=Instantiate(prefab,CellPosition(row,column),Quaternion.identity,blocksRoot).GetComponent<ReflectableBlockView>();view.Setup(this,row,column,currentHp,maximumHp,type);var overrideVisual=view.GetComponent<ReflectableBlockVisualOverride>();if(!overrideVisual)overrideVisual=view.gameObject.AddComponent<ReflectableBlockVisualOverride>();overrideVisual.Configure(data,definition.Data!=null?definition.Data.blockPalette:null);blocks.Add(view);}
        void ApplyStageVisual()
        {
            if (!stageVisualContainer) return;
            if (activeStageVisual) Destroy(activeStageVisual);
            foreach (Transform child in stageVisualContainer) Destroy(child.gameObject);

            var data = ReflectableStageConfig.DataFor(stage);
            var prefab = data ? data.stageVisualPrefab : null;
            if (!prefab)
            {
                Debug.LogError("[StageVisual] Stage " + stage + " has no valid GameObject prefab reference.");
                feedback?.BindStageVisual(null);
                return;
            }

            // Use the non-generic overload so a corrupt serialized asset cannot abort the run
            // with Instantiate<T>'s internal cast. Correct stage assets always resolve to GameObject.
            UnityEngine.Object clone = Instantiate((UnityEngine.Object)prefab, stageVisualContainer);
            activeStageVisual = clone as GameObject;
            if (!activeStageVisual && clone is Component component) activeStageVisual = component.gameObject;
            if (!activeStageVisual)
            {
                if (clone) Destroy(clone);
                Debug.LogError("[StageVisual] Stage " + stage + " resolved to '" + clone?.GetType().Name +
                    "' instead of a GameObject. Reimport its stage prefab and Stage Data asset.");
            }
            feedback?.BindStageVisual(activeStageVisual);
        }
        Vector2 CellPosition(int row,int col)=>(Vector2)gridOrigin.position+new Vector2((col-(columns-1)*.5f)*cellSpacing.x,-row*cellSpacing.y);
        public void HitBlock(ReflectableBlockView block,int damage,bool canTriggerCharacter=true,ArcadeHitKind hitKind=ArcadeHitKind.Direct){if(!block||gameOver||stageTransitioning)return;combo++;maxCombo=Mathf.Max(maxCombo,combo);score+=10+combo/5;if(canTriggerCharacter){TriggerCharacterHit(block,damage);if(character=="ember")burningBlocks[block.GetInstanceID()]=3;}bool critical=UnityEngine.Random.value<(character=="aurora"?.25f:.05f+nyxCriticalBonus);float defense=block.Type==ReflectableBlockType.Elite?.80f:block.Type==ReflectableBlockType.Armored?.85f:block.Type==ReflectableBlockType.Anchor?.80f:1f;float criticalMultiplier=character=="aurora"?2.6f:2f;int dealt=Mathf.Max(1,Mathf.RoundToInt(damage*ReflectableGameBalance.ComboMultiplier(combo)*defense*(critical?criticalMultiplier:1f)));bool destroyedHit=block.HP-dealt<=0;block.ApplyDamage(dealt);feedback?.Hit(combo,block.transform.position,dealt,critical,hitKind,destroyedHit);if(block.HP<=0)DestroyBlock(block,hitKind);RefreshUI();}
        void DestroyBlock(ReflectableBlockView block,ArcadeHitKind hitKind=ArcadeHitKind.Direct){if(!blocks.Remove(block))return;burningBlocks.Remove(block.GetInstanceID());bool boss=block.Type==ReflectableBlockType.Boss;bool finalBossDefeated=boss&&finalBossActive;bool counted=block.Type==ReflectableBlockType.Normal||block.Type==ReflectableBlockType.Tough||block.Type==ReflectableBlockType.Armored||block.Type==ReflectableBlockType.Elite||block.Type==ReflectableBlockType.Anchor;feedback?.Destroyed(block.transform.position,combo,block.Type==ReflectableBlockType.Bomb?ArcadeHitKind.Explosion:hitKind);destroyed++;skillPoints++;Debug.Log("[SP] +1 | Block destroyed | SP "+skillPoints);score+=boss?1000: block.Type==ReflectableBlockType.Gem?250:block.Type==ReflectableBlockType.Bomb?150:100;float progress=stageBlocks/(float)ReflectableStageConfig.For(stage).BlockTarget;int reward=boss?ReflectableGameBalance.BossExperience(block.MaxHP):ReflectableGameBalance.BlockExperience(block.Type,block.MaxHP,progress);int expGain=Mathf.RoundToInt(reward*ReflectableGameBalance.ComboExpMultiplier(combo)*ReflectableStageConfig.For(stage).RewardMultiplier);exp+=expGain;Debug.Log("[EXP] +"+expGain);if(counted&&stageBlocks<ReflectableStageConfig.For(stage).BlockTarget){stageBlocks++;Debug.Log("[Stage] Progress "+stageBlocks+" / "+ReflectableStageConfig.For(stage).BlockTarget);if(stageBlocks>=ReflectableStageConfig.For(stage).BlockTarget){stageBlocks=ReflectableStageConfig.For(stage).BlockTarget;stageClearPending=true;Debug.Log("[Stage] Target reached. Stage clear pending until the current shot resolves.");}else CheckBossMilestone();}if(block.Type==ReflectableBlockType.Gem)gems+=2+(character=="iris"?2:0)+nyxGemBonus;if(block.Type==ReflectableBlockType.Bomb)foreach(var other in blocks.ToArray())if(other&&Mathf.Abs(other.Row-block.Row)<=1&&Mathf.Abs(other.Column-block.Column)<=1)HitBlock(other,Mathf.Max(3,block.MaxHP/2),false,ArcadeHitKind.Explosion);if(boss){bossActive=false;finalBossActive=false;gems+=2;StartCoroutine(BossDefeatedRoutine(finalBossDefeated));}while(exp>=ExpNeeded){exp-=ExpNeeded;int previous=level;level++;Debug.Log("[EXP] Level "+previous+" -> "+level);}StartCoroutine(FadeDestroy(block));RefreshUI();} int ExpNeeded=>ReflectableGameBalance.ExpRequired(level);
        void CheckBossMilestone(){var definition=ReflectableStageConfig.For(stage);if(stageClearPending||stageBlocks>=definition.BlockTarget)return;while(stageBlocks>=nextBossThreshold&&nextBossThreshold<definition.BlockTarget){bossQueued=true;nextBossThreshold+=definition.BossInterval;}if(!bossActive&&bossQueued)SpawnBoss();}
        void SpawnBoss(){if(bossActive||stageTransitioning)return;bossQueued=false;bossActive=true;bossNumber++;bool finalBoss=stageBlocks>=ReflectableStageConfig.For(stage).BlockTarget;finalBossActive=finalBoss;int hp=ReflectableGameBalance.BossHp(stage,bossNumber,finalBoss);int row=2;while(blocks.Exists(b=>b&&b.Row==row&&b.Column==3))row++;CreateBlock(row,3,hp,hp,ReflectableBlockType.Boss);StartCoroutine(BossIncomingRoutine(finalBoss,hp));Debug.Log(finalBoss?"[Stage] Final Boss spawned":"[Boss] Spawned #"+bossNumber+" HP "+hp+" at "+stageBlocks+" blocks.");}
        IEnumerator BossIncomingRoutine(bool finalBoss,int hp){if(stageIntro){stageIntro.SetActive(true);var label=stageIntro.GetComponentInChildren<Text>();if(label)label.text=finalBoss?"FINAL BOSS\nINCOMING":"BOSS INCOMING\n"+stageBlocks+" BLOCKS";yield return new WaitForSecondsRealtime(.85f);stageIntro.SetActive(false);}if(comboText)comboText.text="BOSS  "+hp+" HP";}
        IEnumerator BossDefeatedRoutine(bool defeatedFinalBoss){if(stageIntro){stageIntro.SetActive(true);var label=stageIntro.GetComponentInChildren<Text>();if(label)label.text="BOSS DEFEATED!";yield return new WaitForSecondsRealtime(.55f);stageIntro.SetActive(false);}if(defeatedFinalBoss)yield return StageClearRoutine();else if(bossQueued)SpawnBoss();}
        IEnumerator StageClearRoutine(){if(stageCleared||stageTransitioning)yield break;stageClearPending=false;stageCleared=stageTransitioning=true;state=TurnState.Resolving;UpdatePauseButton();RefreshSkipTurnButton();aiming=false;ResolveActiveProjectiles(false);if(aimPreview)aimPreview.enabled=false;bool finalStage=stage>=ReflectableStageConfig.StageCount;if(!finalStage){ReflectableStageSession.HighestUnlockedStage=Mathf.Max(ReflectableStageSession.HighestUnlockedStage,stage+1);Debug.Log("[Stage] Stage "+stage+" CLEAR");Debug.Log("[Stage] Stage "+(stage+1)+" unlocked");}if(stageIntro){stageIntro.SetActive(true);var label=stageIntro.GetComponentInChildren<Text>();if(label)label.text=finalStage?"FINAL STAGE CLEAR":"STAGE CLEAR!\nSTAGE "+stage+" — "+ReflectableStageSession.GetPresentation(stage).Name;yield return new WaitForSecondsRealtime(.70f);}ClearBlocks();if(!finalStage){yield return new WaitForSecondsRealtime(.25f);StartStage(stage+1);}else{Save();if(stageIntro)stageIntro.SetActive(false);state=TurnState.Paused;RefreshSkipTurnButton();}}
        void CheckStageClear(){}
        void TriggerCharacterHit(ReflectableBlockView origin,int currentDamage){if(character=="alice")StartCoroutine(AliceHolyBeams(origin,currentDamage));else if(character=="marina")foreach(var target in blocks.ToArray())if(target&&target!=origin&&Mathf.Abs(target.Row-origin.Row)<=1&&Mathf.Abs(target.Column-origin.Column)<=1)HitBlock(target,Mathf.Max(1,Mathf.RoundToInt(currentDamage*.30f)),false,ArcadeHitKind.Splash);}
        IEnumerator AliceHolyBeams(ReflectableBlockView origin,int currentDamage){if(!origin)yield break;var directions=new[]{Vector2Int.up,Vector2Int.down,Vector2Int.left,Vector2Int.right};int beamDamage=Mathf.Max(1,Mathf.RoundToInt(currentDamage*.40f));foreach(var direction in directions){var end=(Vector2)origin.transform.position+new Vector2(direction.x*2.4f,direction.y*1.32f)*12f;StartCoroutine(LightBeam(origin.transform.position,end));for(int step=1;step<=12;step++){var target=blocks.Find(b=>b&&b!=origin&&b.Row==origin.Row-direction.y*step&&b.Column==origin.Column+direction.x*step);if(target)HitBlock(target,beamDamage,false,ArcadeHitKind.Beam);}}yield return null;}
        IEnumerator LightBeam(Vector3 start,Vector3 end){feedback?.Beam(start,end,combo);yield return new WaitForSecondsRealtime(.22f);}
        public void RegisterRicochet(ReflectableProjectile projectile){if(!projectile)return;ricochets++;float bonus=.08f+ricochet*.035f+nyxRicochetBonus;projectile.AddDamage(Mathf.Max(2,Mathf.RoundToInt(projectile.Damage*bonus)));feedback?.Ricochet(projectile.transform.position,combo);if(character=="lunaria")projectile.ApplyLunariaRicochet();}
        public void BuyUpgrade(string id){if(id!="Power"&&id!="Ricochet"&&id!="Extra Ball")return;int value=UpgradeLevel(id);int cost=UpgradeCost(id,value);if(!GameplayInputEnabled||skillPoints<cost){RefreshUI();return;}skillPoints-=cost;if(id=="Power")power++;else if(id=="Ricochet")ricochet++;else extraBall++;if(character=="celestia")GrantCelestiaBonus();gameplayHud?.UpgradePurchased(id);RefreshUI();}
        public void SkipTurn(){if(!CanSkipTurn)return;bool firing=state==TurnState.Firing;skippingTurn=true;aiming=false;state=TurnState.Resolving;turnFired=false;if(aimPreview)aimPreview.enabled=false;RefreshSkipTurnButton();Debug.Log("[Turn] SKIP requested"+(firing?" during projectile simulation":" during aiming"));if(firing)ForceClearAllProjectiles();StartCoroutine(SkipTurnRoutine());}
        IEnumerator SkipTurnRoutine(){feedback?.ComboEnded(combo);combo=0;ending=false;yield return EndTurn();skippingTurn=false;RefreshSkipTurnButton();Debug.Log("[Turn] Skip completed");}
        public void ForceClearAllProjectiles(){var projectiles=FindObjectsByType<ReflectableProjectile>(FindObjectsSortMode.None);Debug.Log("[Turn] Force-clearing active projectiles: "+projectiles.Length);foreach(var projectile in projectiles)projectile.ForceResolve(false);activeProjectileIds.Clear();activeProjectiles=0;}
        void ResolveActiveProjectiles(bool notifyOwner){if(notifyOwner){var projectiles=FindObjectsByType<ReflectableProjectile>(FindObjectsSortMode.None);foreach(var projectile in projectiles)projectile.ForceResolve(true);return;}ForceClearAllProjectiles();}
        public void OpenCharacterPanel(){if(gameOver||!characterPanel||!characterGacha)return;gameplayHud?.ClearCharacterBadge();pausedState=state;state=TurnState.Paused;Time.timeScale=0;characterPanel.SetActive(true);characterGacha.Open(characterPresenter?characterPresenter.CurrentData:null,characterPresenter?characterPresenter.Database:null,gems);RefreshSkipTurnButton();}
        public void CloseCharacterPanel(){if(gachaRoutine!=null)return;if(characterPanel)characterPanel.SetActive(false);if(!gameOver){Time.timeScale=1;state=pausedState;}RefreshSkipTurnButton();}
        public void DrawCharacter(){if(gachaRoutine!=null||!characterGacha||!characterGacha.Config)return;int cost=characterGacha.Config.drawCost;if(gems<cost){characterGacha.ShowInsufficientCurrency(gems);return;}CharacterDatabase database=characterPresenter?characterPresenter.Database:null;CharacterData drawn=characterGacha.Config.Roll(database);if(!drawn){Debug.LogError("[CharacterGacha] Character database has no valid draw entries.");return;}gachaRoutine=StartCoroutine(DrawCharacterRoutine(drawn,cost));}
        IEnumerator DrawCharacterRoutine(CharacterData drawn,int cost){characterGacha.SetDrawInteractable(false);gems-=cost;bool duplicate=drawn.characterId==character;string compensation="";if(duplicate){var config=characterGacha.Config;if(config.duplicateCompensation==DuplicateCompensationType.SkillPoints&&config.duplicateCompensationAmount>0){skillPoints+=config.duplicateCompensationAmount;compensation="+"+config.duplicateCompensationAmount+" SP";}else if(config.duplicateCompensation==DuplicateCompensationType.Gems&&config.duplicateCompensationAmount>0){gems+=config.duplicateCompensationAmount;compensation="+"+config.duplicateCompensationAmount+" GEMS";}}else ActivateCharacter(drawn);characterGacha.RefreshCurrency(gems);RefreshUI();Save();yield return characterGacha.PlayReveal(drawn,duplicate,compensation);gachaRoutine=null;}
        void ActivateCharacter(CharacterData data){if(!data)return;CharacterData previous=characterPresenter?characterPresenter.CurrentData:null;string previousName=previous?previous.displayName:character;Debug.Log("[CharacterGacha] Previous character removed: "+previousName);burningBlocks.Clear();nyxDamageBonus=nyxRicochetBonus=nyxCriticalBonus=0f;nyxExtraBalls=nyxGemBonus=0;character=data.characterId;rank=Mathf.Max(1,data.startingLevel);CharacterProgression.SetActiveCharacter(character,rank);characterPresenter?.Present(character);feedback?.BindCharacter(characterPresenter);Debug.Log("[CharacterGacha] New character activated: "+data.displayName);Debug.Log("[CharacterGacha] Passive enabled: "+data.CutInAbilityName);}
        public void TogglePause(){if(gameOver||stageTransitioning||stageCleared)return;if(pauseSettingsPanel&&pauseSettingsPanel.activeInHierarchy){ClosePauseSettings();return;}if(mainMenuConfirmPanel&&mainMenuConfirmPanel.activeInHierarchy){CancelMainMenu();return;}if(pausePanel&&pausePanel.activeInHierarchy)ResumeGame();else PauseGame();}
        public void PauseGame(){if(gameOver||stageTransitioning||stageCleared||Time.timeScale==0)return;pausedState=state;state=TurnState.Paused;Time.timeScale=0;if(pausePanel)pausePanel.SetActive(true);UpdatePauseButton();RefreshSkipTurnButton();}
        public void ResumeGame(){if(pauseSettingsPanel)pauseSettingsPanel.SetActive(false);if(mainMenuConfirmPanel)mainMenuConfirmPanel.SetActive(false);if(pausePanel)pausePanel.SetActive(false);Time.timeScale=1;if(!gameOver)state=pausedState;UpdatePauseButton();RefreshSkipTurnButton();}
        public void OpenPauseSettings(){if(!pausePanel||!pausePanel.activeInHierarchy)return;pausePanel.SetActive(false);if(pauseSettingsPanel)pauseSettingsPanel.SetActive(true);}
        public void ClosePauseSettings(){if(pauseSettingsPanel)pauseSettingsPanel.SetActive(false);if(!gameOver&&pausePanel)pausePanel.SetActive(true);}
        public void RequestMainMenu(){if(!pausePanel||!pausePanel.activeInHierarchy)return;pausePanel.SetActive(false);if(mainMenuConfirmPanel)mainMenuConfirmPanel.SetActive(true);}
        public void CancelMainMenu(){if(mainMenuConfirmPanel)mainMenuConfirmPanel.SetActive(false);if(!gameOver&&pausePanel)pausePanel.SetActive(true);}
        public void ConfirmMainMenu(){Save();Time.timeScale=1;SceneManager.LoadScene("MainMenu");}
        public void MainMenu(){Time.timeScale=1;SceneManager.LoadScene("MainMenu");}public void Retry(){Time.timeScale=1;StartNewRun();}
        void GameOver(){gameOver=true;feedback?.ComboEnded(combo);state=TurnState.GameOver;aiming=false;if(aimPreview)aimPreview.enabled=false;if(pausePanel)pausePanel.SetActive(false);if(pauseSettingsPanel)pauseSettingsPanel.SetActive(false);if(mainMenuConfirmPanel)mainMenuConfirmPanel.SetActive(false);UpdatePauseButton();RefreshSkipTurnButton();PlayerPrefs.SetInt("ReflectableBest",Mathf.Max(PlayerPrefs.GetInt("ReflectableBest",0),score));PlayerPrefs.Save();DeleteRunSaveFiles();if(gameOverText)gameOverText.text=$"GAME OVER\nScore {score}\nBest {PlayerPrefs.GetInt("ReflectableBest",0)}\nTurn {turn}\nBlocks {destroyed}\nMax Combo {maxCombo}\nRicochets {ricochets}";if(gameOverPanel)gameOverPanel.SetActive(true);}
        void DeleteRunSaveFiles(){foreach(var path in new[]{SavePath,SaveBackupPath,SaveTempPath})try{if(File.Exists(path))File.Delete(path);}catch(Exception exception){Debug.LogWarning("[Save] Could not delete "+path+": "+exception.Message);}}
        void Save()
        {
            var d=new ReflectableRunSave{valid=true,stage=stage,turn=turn,hp=hp,maxHp=maxHp,score=score,gems=gems,level=level,exp=exp,skillPoints=skillPoints,power=power,ricochet=ricochet,extraBall=extraBall,maxCombo=maxCombo,destroyed=destroyed,stageBlocks=stageBlocks,ricochets=ricochets,lightDamage=lightDamage,lightRange=lightRange,lightPierce=lightPierce,character=character,rank=rank};
            foreach(var b in blocks)if(b)d.blocks.Add(new ReflectableCellSave{row=b.Row,column=b.Column,hp=b.HP,maxHp=b.MaxHP,type=b.Type});
            try
            {
                File.WriteAllText(SaveTempPath,JsonUtility.ToJson(d));
                if(File.Exists(SavePath))File.Replace(SaveTempPath,SavePath,SaveBackupPath);
                else File.Move(SaveTempPath,SavePath);
            }
            catch(Exception exception)
            {
                Debug.LogError("[Save] Atomic save failed: "+exception.Message);
                try{if(File.Exists(SaveTempPath))File.Delete(SaveTempPath);}catch(Exception cleanupException){Debug.LogWarning("[Save] Temporary-file cleanup failed: "+cleanupException.Message);}
            }
        }
        void RefreshUI(){int displayStage=Mathf.Max(1,stage);var stageConfig=ReflectableStageConfig.For(displayStage);if(hpText)hpText.text=$"HP {hp} / {maxHp}";if(scoreText)scoreText.text=$"SCORE {score}";if(gemsText)gemsText.text=$"GEMS {gems}";if(turnText)turnText.text=$"STAGE {displayStage}  •  {Mathf.Min(stageBlocks,stageConfig.BlockTarget)} / {stageConfig.BlockTarget} BLOCKS\nTURN {turn}";var boss=blocks.Find(b=>b&&b.Type==ReflectableBlockType.Boss);if(comboText&&!feedback)comboText.text=boss?$"BOSS\n{boss.HP} / {boss.MaxHP}":combo>0?$"{combo} HIT!":"";if(levelText)levelText.text=$"LV {level}  EXP {exp}/{ExpNeeded}  SP {skillPoints}\nBUILD PROGRESSION";if(characterText)characterText.text=$"{CharacterDisplayName()}  Lv.{rank}\n{AbilityName()}";RefreshUpgradeButtons();RefreshSkipTurnButton();if(gameplayHud){var data=characterPresenter?characterPresenter.CurrentData:null;gameplayHud.Refresh(hp,maxHp,displayStage,ReflectableStageSession.GetPresentation(displayStage).Name,Mathf.Min(stageBlocks,stageConfig.BlockTarget),stageConfig.BlockTarget,turn,score,gems,skillPoints,data,rank,power,UpgradeCost("Power",power),ricochet,UpgradeCost("Ricochet",ricochet),extraBall,UpgradeCost("Extra Ball",extraBall),GameplayInputEnabled);}}
        void RefreshUpgradeButtons(){SetUpgradeButton(powerButton,"POWER",power,UpgradeCost("Power",power));SetUpgradeButton(ricochetButton,"RICOCHET",ricochet,UpgradeCost("Ricochet",ricochet));SetUpgradeButton(extraBallButton,"EXTRA BALL",extraBall,UpgradeCost("Extra Ball",extraBall));if(characterButton){characterButton.interactable=!gameOver;SetButtonText(characterButton,"SUMMON");}}
        int UpgradeLevel(string id)=>id=="Power"?power:id=="Ricochet"?ricochet:extraBall;
        int UpgradeCost(string id,int level){var standard=new[]{1,2,4,7,11,16,23,31};var extra=new[]{5,10,18,30,45,65,90,120};var curve=id=="Extra Ball"?extra:standard;return level<curve.Length?curve[level]:curve[curve.Length-1]+(level-curve.Length+1)*(id=="Extra Ball"?35:10);}
        void SetUpgradeButton(Button button,string title,int value,int cost){if(!button)return;button.interactable=GameplayInputEnabled&&skillPoints>=cost;SetButtonText(button,$"{title}\nLv. {value}\n{cost} SP");}
        static void SetButtonText(Button button,string value){var label=button.GetComponentInChildren<Text>();if(label)label.text=value;}
        IEnumerator StageIntroRoutine(){if(stageIntro){stageIntro.SetActive(true);var label=stageIntro.GetComponentInChildren<Text>();if(label)label.text=$"STAGE {stage}\n{ReflectableStageSession.GetPresentation(stage).Name}";var group=stageIntro.GetComponent<CanvasGroup>();if(group){for(float t=0;t<.18f;t+=Time.unscaledDeltaTime){group.alpha=t/.18f;yield return null;}yield return new WaitForSecondsRealtime(.42f);for(float t=0;t<.18f;t+=Time.unscaledDeltaTime){group.alpha=1f-t/.18f;yield return null;}}stageIntro.SetActive(false);}stageTransitioning=false;UpdatePauseButton();BeginTurn();}
        bool BlockReachedPlayerDamagePlane(ReflectableBlockView block){var blockCollider=block?block.GetComponent<Collider2D>():null;var playerCollider=characterPresenter?characterPresenter.GameplayHitbox:null;return blockCollider&&playerCollider&&blockCollider.bounds.min.y<=playerCollider.bounds.max.y;}
        int PlayerContactDamage(ReflectableBlockType type)=>type==ReflectableBlockType.Tough?15:type==ReflectableBlockType.Armored?20:type==ReflectableBlockType.Elite?25:type==ReflectableBlockType.Anchor?30:type==ReflectableBlockType.Boss?45:type==ReflectableBlockType.Gem||type==ReflectableBlockType.Bomb?5:10;
        void SetHealth(int current,int maximum){maxHp=Mathf.Max(1,maximum);hp=Mathf.Clamp(current,0,maxHp);HealthChanged?.Invoke(hp,maxHp);RefreshUI();}
        public void TakePlayerDamage(int damage){if(gameOver||damage<=0)return;SetHealth(hp-damage,maxHp);Debug.Log("[Player] Damage "+damage+" | HP "+hp+" / "+maxHp);StartCoroutine(PlayerDamageFeedback());if(hp<=0)GameOver();}
        void DamagePlayerFromBlock(ReflectableBlockView block){if(!block)return;Debug.Log("[BlockDamage] Block ID "+block.GetInstanceID()+" reached Player | resolved = "+block.HasResolvedPlayerContact);if(!block.TryMarkPlayerDamage()){Debug.Log("[BlockDamage] Block ID "+block.GetInstanceID()+" was already resolved.");return;}int damage=PlayerContactDamage(block.Type);Debug.Log("[BlockDamage] Applying "+damage+" damage from Block ID "+block.GetInstanceID());TakePlayerDamage(damage);blocks.Remove(block);Destroy(block.gameObject);Debug.Log("[BlockDamage] Block ID "+block.GetInstanceID()+" resolved");}
        void ResolveMissedPlayerBlock(ReflectableBlockView block,bool failSafe){if(!block||!block.TryMarkPlayerDamage())return;blocks.Remove(block);Destroy(block.gameObject);Debug.Log(failSafe?"[Block] Bottom fail-safe triggered for Block ID "+block.GetInstanceID():"[Block] Missed player and resolved");}
        IEnumerator PlayerRecoil(){var visual=characterPresenter?characterPresenter.CurrentVisual:null;if(!visual)yield break;var start=visual.localScale;var hitScale=Vector3.Scale(start,new Vector3(1.12f,.82f,1f));for(float t=0;t<.06f;t+=Time.unscaledDeltaTime){visual.localScale=Vector3.Lerp(start,hitScale,t/.06f);yield return null;}for(float t=0;t<.12f;t+=Time.unscaledDeltaTime){visual.localScale=Vector3.Lerp(hitScale,start,t/.12f);yield return null;}if(visual)visual.localScale=start;}
        IEnumerator PlayerDamageFeedback(){feedback?.Shake(.09f,.18f);var visual=characterPresenter?characterPresenter.CurrentVisual:null;var renderers=visual?visual.GetComponentsInChildren<SpriteRenderer>(true):Array.Empty<SpriteRenderer>();var original=new Color[renderers.Length];for(int i=0;i<renderers.Length;i++)original[i]=renderers[i].color;var hpScale=hpText?hpText.rectTransform.localScale:Vector3.one;for(float t=0;t<.09f;t+=Time.unscaledDeltaTime){float p=t/.09f;for(int i=0;i<renderers.Length;i++)if(renderers[i])renderers[i].color=Color.Lerp(original[i],new Color(1f,.28f,.45f,1f),p);if(hpText)hpText.rectTransform.localScale=Vector3.Lerp(hpScale,hpScale*1.18f,p);yield return null;}for(float t=0;t<.15f;t+=Time.unscaledDeltaTime){float p=t/.15f;for(int i=0;i<renderers.Length;i++)if(renderers[i])renderers[i].color=Color.Lerp(new Color(1f,.28f,.45f,1f),original[i],p);if(hpText)hpText.rectTransform.localScale=Vector3.Lerp(hpScale*1.18f,hpScale,p);yield return null;}if(hpText)hpText.rectTransform.localScale=hpScale;}
        void UpdatePauseButton(){if(pauseButton)pauseButton.gameObject.SetActive(!gameOver&&!stageTransitioning&&!stageCleared);}
        IEnumerator MovePlayerToReturn(float returnX){if(!player)yield break;var start=player.position;var target=new Vector3(Mathf.Clamp(returnX,left+.45f,right-.45f),start.y,start.z);for(float t=0;t<.18f;t+=Time.deltaTime){player.position=Vector3.Lerp(start,target,Mathf.SmoothStep(0,1,t/.18f));yield return null;}if(player)player.position=target;}
        IEnumerator FadeDestroy(ReflectableBlockView block){var collider=block.GetComponent<Collider2D>();if(collider)collider.enabled=false;var visual=block.transform.Find("Visual")??block.transform;var renderers=visual.GetComponentsInChildren<SpriteRenderer>();var start=visual.localScale;for(float t=0;t<.18f;t+=Time.deltaTime){var p=t/.18f;if(visual)visual.localScale=Vector3.Lerp(start*1.12f,Vector3.zero,p);foreach(var item in renderers)if(item){var c=item.color;c.a=1f-p;item.color=c;}yield return null;}if(block)Destroy(block.gameObject);}
        void ApplyBurnDamage(){foreach(var block in blocks.ToArray()){if(!block)continue;int turns;if(!burningBlocks.TryGetValue(block.GetInstanceID(),out turns))continue;HitBlock(block,Mathf.Max(1,ProjectileDamage()/5),false,ArcadeHitKind.Burn);turns--;if(turns<=0||!block||!blocks.Contains(block))burningBlocks.Remove(block.GetInstanceID());else burningBlocks[block.GetInstanceID()]=turns;}}
        void RollNyxBuff(){nyxDamageBonus=nyxRicochetBonus=nyxCriticalBonus=0f;nyxExtraBalls=nyxGemBonus=0;if(character!="nyx")return;switch(UnityEngine.Random.Range(0,5)){case 0:nyxDamageBonus=.25f;break;case 1:nyxRicochetBonus=.12f;break;case 2:nyxCriticalBonus=.15f;break;case 3:nyxExtraBalls=1;break;default:nyxGemBonus=1;break;}}
        void GrantCelestiaBonus(){switch(UnityEngine.Random.Range(0,5)){case 0:power++;break;case 1:ricochet++;break;case 2:extraBall++;break;case 3:gems+=2;break;default:skillPoints++;break;}Debug.Log("[Character] Celestia granted an additional upgrade bonus.");}
        string CharacterDisplayName(){var data=characterPresenter?characterPresenter.CurrentData:null;return data?data.displayName:character.ToUpperInvariant();}
        string AbilityName(){var data=characterPresenter?characterPresenter.CurrentData:null;return data?data.role.ToString().ToUpperInvariant():"SPLASH";}
        string AbilityDescription(){var data=characterPresenter?characterPresenter.CurrentData:null;return data?data.passiveAbility:"Projectile impacts deal splash damage around the hit Block.";}
        void DrawPreview(Vector2 direction)
        {
            if (!aimPreview || !firePoint)
                return;

            const int maximumSegments = 5;
            var points = new Vector3[maximumSegments + 1];
            var point = (Vector2)firePoint.position;
            var velocity = direction.normalized;
            points[0] = point;
            var count = 1;

            for (var i = 0; i < maximumSegments; i++)
            {
                // Offset the origin by the projectile radius so this ray starts outside the player.
                var hit = Physics2D.Raycast(point + velocity * .14f, velocity, 20f);
                if (!hit.collider)
                {
                    points[count++] = point + velocity * 4f;
                    break;
                }

                point = hit.point;
                points[count++] = point;
                if (hit.collider.isTrigger || hit.collider.name == "BottomBoundary")
                    break;

                velocity = Vector2.Reflect(velocity, hit.normal).normalized;
            }

            aimPreview.positionCount = count;
            aimPreview.SetPositions(points);
        }
        void ClearBlocks(){foreach(var b in blocks)if(b)Destroy(b.gameObject);blocks.Clear();burningBlocks.Clear();}void OnDrawGizmosSelected(){if(!gridOrigin)return;Gizmos.color=Color.cyan;for(int r=0;r<rows;r++)for(int c=0;c<columns;c++)Gizmos.DrawWireCube(CellPosition(r,c),new Vector3(cellSpacing.x*.9f,cellSpacing.y*.85f,.05f));if(!drawPlayerDamageDebug||characterPresenter==null||characterPresenter.GameplayHitbox==null)return;var bounds=characterPresenter.GameplayHitbox.bounds;Gizmos.color=Color.yellow;Gizmos.DrawWireCube(bounds.center,bounds.size);Gizmos.color=Color.red;Gizmos.DrawLine(new Vector3(left,bounds.max.y,0),new Vector3(right,bounds.max.y,0));}
    }
}
